engines:
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: .eslintrc.json
ratings:
  paths:
  - bin/**/*.js
  - lib/**/*.js
exclude_paths:
- "node_modules/**"
- "coverage/**"
